"""TabelaDist

Revision ID: f66112ab2525
Revises: 023e7dca5371
Create Date: 2026-04-24 10:28:43.327624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f66112ab2525'
down_revision: Union[str, Sequence[str], None] = '023e7dca5371'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('distribuidoras',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('date_gdb', sa.Integer(), nullable=False),
    sa.Column('dist_name', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', 'date_gdb')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('distribuidoras')
    # ### end Alembic commands ###
